openapi: "3.0.0"
info:
  version: 1.0.0
  title: attachmentmigration1
  license:
    name: MIT
servers:
  - url: https://attmigration-dev.azurewebsites.net
paths:
  /api/orchestrators/attachmentmigrationorchestrator:
    post:
      tags:
        - s3att
      summary: S3migration
      operationId: s3migration
      responses:
        '200':
          description: success
components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]
