openapi: "3.0.0"
info:
  version: 1.0.0
  title: attachmentmigration2
  license:
    name: MIT
servers:
  - url: https://attmigration-dev.azurewebsites.net
paths:
  /api/orchestrators/attachmentmigrationorchestrator:
    post:
      tags:
        - s3att
      summary: S3migration
      operationId: s3migration
      responses:
        '200':
          description: success
        '401':
          $ref: '#/components/responses/UnauthorizedError'          
components:
  securitySchemes:
    basicAuth:     # <-- arbitrary name for the security scheme
      type: http
      scheme: basic
  responses:
    UnauthorizedError:
      description: Authentication information is missing or invalid
      headers:
        WWW_Authenticate:
          schema:
            type: string      
security:
- basicAuth: []  # <-- use the same name here
